hyochan/expo-iap

src/index.ts, src/modules/ios.ts, src/useIap.ts
Port https://github.com/hyochan/react-native-iap/blob/main/src/hooks/useIAP.ts
=> feat: useIap hook

src/index.ts
This PR resolves an issue in `finishTransaction` where an extra `developerPayloadAndroid` argument caused an error on Android (`[Error: Received 2 arguments, but 1 was expected]`). It removes the unnecessary parameter and enhances the function to handle both consumable and non-consumable purchases by calling `consumeProduct` or `acknowledgePurchase` based on `isConsumable`. 
- **Changes:**
- Removed `developerPayloadAndroid` from `finishTransaction` params.
- Added logic to call `acknowledgePurchase` for non-consumable purchases on Android.
- **Fixes:** Ensures compatibility with Google Play Billing Library 6.0.1+ and aligns with the Kotlin module's `consumeProduct` signature.
- **Tested:** Should prevent purchase cancellations after 3 minutes for consumables and properly acknowledge …
=> fix(Android): finishTransaction and add acknowledge support

android/src/main/java/expo/modules/iap/ExpoIapModule.kt, iap.md, ios/ExpoIapModule.swift, src/ExpoIap.types.ts, src/index.ts, src/types/ExpoIapAndroid.types.ts
- Unified `transactionReceipt` for receipt validation across platforms:
- **Android**: Uses raw purchase data in JSON format (e.g., `originalJson`).
- **iOS**: Uses JWS format via `jwsReceipt` from `jsonRepresentation` (see [App Store Server API](https://developer.apple.com/documentation/appstoreserverapi)).
- Added `jwsReceipt` to `transactionReceipt` for iOS, leveraging StoreKit 2's `jsonRepresentation`.
- Renamed `purchaseToken` to `purchaseTokenAndroid` in Android for platform-consistent naming.
- Updated relevant Android and iOS code to reflect these changes.
=> Add `jwsReceipt` and Rename to `purchaseTokenAndroid`

android/src/main/java/expo/modules/iap/ExpoIapModule.kt, android/src/main/java/expo/modules/iap/PlayUtils.kt, package.json, src/index.ts, src/useIap.ts
This PR fixes an Android IAP crash and improves transaction handling:
1. **Safe Event Handling**: Wrapped `sendEvent` in `try-catch` to prevent `NullPointerException` crashes in `ExpoIapModule` (Commit: `fix: safely handle events in android mod`).
2. **Transaction Fix**: Enhanced `finishTransaction` in `useIap` for stable async flow (Commit: `fix: finishTransaction in useIap`).
=> Fix Android IAP Crash & Transaction Flow

android/src/main/java/expo/modules/iap/ExpoIapModule.kt, src/ExpoIap.types.ts, src/types/ExpoIapIos.types.ts
- Added `currency` and `displayPrice` at the top level of `ProductDetails` response.
- Uses `oneTimePurchaseOfferDetails` or falls back to `subscriptionOfferDetails`’s first pricing phase.
- Updated `ProductBase` TypeScript type with `displayPrice` and `currency`.
- Aligns with iOS, where these fields are top-level (see below).
```kotlin
val currency = productDetails.oneTimePurchaseOfferDetails?.priceCurrencyCode
?: productDetails.subscriptionOfferDetails?.firstOrNull()?.pricingPhases?.pricingPhaseList?.firstOrNull()?.priceCurrencyCode
val displayPrice = productDetails.oneTimePurchaseOfferDetails?.formattedPrice
?: productDetails.subscriptionOfferDetails?.firstOrNull()?.pricingPhases?.pricingPhaseList?.firstOrNull()?.formattedPrice
mapOf("currency" to currency, "displayPrice" to …
```
=> Add top-level currency and displayPrice to product details response

ios/ExpoIapModule.swift
Closes #27
I want to use expo-iap, so I fix this issue.
Without this, receipt verification is not possible.
=> fix(ios): signature encoding

ios/ExpoIapModule.swift, src/types/ExpoIapIos.types.ts
Possible fix to #34 
As stated in the StoreKit [documentation](https://developer.apple.com/documentation/storekit/transaction#Verify-transactions):
> To perform your own validation on the device, use the verification result’s jwsRepresentation string, and use the provided convenience properties headerData, payloadData, and signatureData. For added control and security, send the jwsRepresentation to your server to verify.
However, the current return value of the library's `requestPurchase` only returns the `jsonRepresentation` of the `Transaction` object, and not `jwsRepresentation` of the verification result, which makes it more complicated to implement a server-side verification.
With this change, user can correctly get the required `JWS` that they can use to implement their own …
=> feat: add verified jws representation to serializeTransaction

ios/ExpoIapModule.swift, src/types/ExpoIapIos.types.ts
fixes #44 ?
ports https://github.com/hyochan/react-native-iap/pull/2874 to `expo-iap`
which makes `getAvailableItems` includes `jwsRepresentationIos` in the returned map.
Also deletes `verificationResultIos` in the type since its not used anywhere
=> add jwsRepresentationIos to the returned map of getAvailableItems

example/App.tsx, example/app.json, ios/ExpoIapModule.swift, package.json, src/modules/ios.ts, src/useIap.ts
This PR addresses an issue where changing subscription renewal status through iOS subscription management UI (via `showManageSubscriptions()`) didn't emit any events to the app. This made it difficult for apps to stay in sync with subscription status changes without manually polling.
When users changed their subscription renewal status (for example, toggling off auto-renewal) through Apple's subscription management UI, the app had no way of knowing about this change. This resulted in stale data being displayed to the user until the app was restarted or manual API calls were made.
The solution implements a polling mechanism that runs after the subscription management UI is dismissed:
1. Before showing the management UI, we collect all subscription product IDs
2. After the UI is dismissed, …
=> fix: subscription renewal status not emitting events

example/App.tsx, ios/ExpoIapModule.swift, package.json, src/modules/ios.ts, src/useIap.ts
This PR adds receipt validation capabilities to the expo-iap library, enabling developers to validate purchases directly on iOS using StoreKit 2's built-in verification mechanisms, while maintaining the existing Android validation functionality.
- Added `validateReceiptIos` method that leverages StoreKit 2's verification system
- Added utility methods for more granular validation: `getReceiptData`, `isTransactionVerified`, and `getTransactionJws`
- Extended `useIAP` hook with a platform-agnostic `validateReceipt` method
- Updated example app with receipt validation demonstration
- StoreKit 2 has built-in receipt validation through its VerificationResult API
- New iOS implementation returns comprehensive validation information:
- Receipt validity status (isValid)
- Base64 encoded receipt …
=> Add iOS receipt validation functionality

ios/ExpoIapModule.swift, package.json
Fixes #51
This PR resolves an issue where the `jwsRepresentationIos` field was missing from the result of the `getAvailablePurchases()` function on iOS devices. This issue specifically occurred in the Sandbox environment on devices running iOS 15+ with StoreKit 2.
* Added debug logs in the iOS native code to trace where the JWS representation was being omitted
* Improved handling of `jwsRepresentationIos` in the `getAvailableItems()` method
* Enhanced the serialization logic for JWS representation in the `serializeTransaction()` function
* Run the app on a physical iOS 15+ device
* Test in-app purchases in the Sandbox environment
* Verify that the `getAvailablePurchases()` result includes the `jwsRepresentationIos` field
* Confirm that the purchase validation flow works correctly
This …
=> fix: return jwsRepresentationIos in getAvailableItems

ios/ExpoIapModule.swift
Belongs to: https://github.com/hyochan/expo-iap/issues/59
=> [IOS] FIx IOS exceptions

iap.md
Removed managed workflow link because it redirected to a page that is 404. The archive link from expo has been moved or removed maybe?
=> Removed dead links redirecting to managed vs bare documentation.

iap.md
Removed "link-to-docs" with actual link to docs. I believe "link-to-docs" was just a placeholder which was redirecting to 404.
=> Fix the broken documentation link in the documentation.

README.md, docs/SETUP_GUIDE.md
Addresses setup requirements from [discussion #72](https://github.com/hyochan/expo-iap/discussions/72) by adding a comprehensive beginner's guide.
Added `docs/SETUP_GUIDE.md` covering Google Play Store setup, Apple App Store configuration, Expo project setup, backend receipt validation, and Expo Dev Client integration. The guide provides step-by-step instructions from store configuration to production deployment with practical examples and troubleshooting tips.
Also reorganized documentation structure and updated README to prominently feature the new setup guide
=> docs: add setup guide

android/src/main/java/expo/modules/iap/ExpoIapModule.kt, android/src/main/java/expo/modules/iap/Types.kt, ios/ExpoIapModule.swift, ios/Types.swift
Refactored error code management to eliminate duplication and improve maintainability. Created dedicated `Types.kt` (Android) and updated `Types.swift` (iOS) files with single-source error code definitions using efficient mapping patterns.
Both platforms now use identical file structures where error codes are defined once and automatically generate all necessary constants and exports. This eliminates the previous duplication where each error code was defined twice.
No breaking changes - all existing error
=> refactor: centralize error codes in Types files

ios/ExpoIapModule.swift
For consistency with the typings and `transactionId`.
StoreKit [Transaction.originalID](https://developer.apple.com/documentation/storekit/transaction/originalid) returns as a UInt64, however the typings show that `originalTransactionIdentifierIos` returns as a string:
https://github.com/hyochan/expo-iap/blob/ca7c409ec4ecf3c7ae000c1537b015df9af06df5/src/types/ExpoIapIos.types.ts#L107-L112
Either we need to update the typings or update the Swift file. 
Note that this wasn't compiled or tested. I'm using the current version of expo-iap and wrapping the value with `String(purchase.originalTransactionId)` on the JS side.
=> fix(ios): cast originalTransactionIdentifierIos to string

android/src/main/java/expo/modules/iap/ExpoIapModule.kt, docs/bun.lock, docs/docs/api/methods/core-methods.md, example/app/index.tsx, ios/ExpoIapModule.swift, src/index.ts
This PR adds support for getStoreFront which existed in react-native-iap and was not ported to expo-iap
=> feat: add offer getStoreFront support for iOS and Android

docs/docs/api/methods/core-methods.md, ios/ExpoIapModule.swift, src/index.ts, src/modules/ios.ts, src/types/ExpoIapIos.types.ts
- Add AppTransaction TypeScript type definition
- Implement native getAppTransaction method in Swift module
- Export getAppTransaction function from ios module
- Add comprehensive documentation for the new API
- Fix appTransactionID field name to match Apple's API
Port of [react-native-iap PR #2969](https://github.com/hyochan/react-native-iap/pull/2969)
=> feat(ios): add getAppTransaction support for iOS 16.0+

docs/blog/2025-07-21-v2-6-0-release.md, docs/docs/api/methods/core-methods.md, docs/docs/api/use-iap.md, docs/docs/guides/migration.md, src/index.ts, src/useIap.ts
This PR updates the purchase history method naming to use the plural form for better consistency with the `useIAP` hook.
- ✅ Add new `getPurchaseHistories()` function (plural)
- ✅ Deprecate `getPurchaseHistory()` function (singular) with warning
- ✅ Update `useIAP` hook to use `getPurchaseHistories` internally
- ✅ Update all documentation to reflect the naming change
- ✅ Add deprecation notices in docs
⚠️ `getPurchaseHistory()` is now deprecated and will be removed in version 3.0.0. Please use `getPurchaseHistories()` instead.
```typescript
import { getPurchaseHistory } from 'expo-iap';
const history = await getPurchaseHistory();
```
```typescript
import { getPurchaseHistories } from 'expo-iap';
const histories = await getPurchaseHistories();
```
```typescript
const { purchaseHistories, …
```
=> fix: update purchase history method naming to plural form

android/build.gradle, android/src/main/java/expo/modules/iap/ExpoIapModule.kt, docs/blog/2025-07-22-v2-7-0-release.md, docs/docs/guides/purchases.md, example/app.json, example/app/purchase-flow.tsx, example/app/subscription-flow.tsx, package.json, src/index.ts
- Update billing-ktx dependency from 7.0.0 to 8.0.0
- Fix Kotlin compatibility by setting JVM target to 17
- Update queryProductDetailsAsync to use QueryProductDetailsResult
- Add PendingPurchasesParams for enablePendingPurchases
- Add deprecation warning for getPurchaseHistories on Android
- Update getPurchaseHistories to return empty array on Android
- Add blog post documenting v8 changes and migration guide
BREAKING CHANGE: getPurchaseHistories no longer returns purchase history on Android. Use getAvailablePurchases instead for active purchases.
=> feat(android): update to Google Play Billing Library v8.0.0

ios/ExpoIapModule.swift, src/types/ExpoIapIos.types.ts
- Fix iOS compatibility issue by adding proper availability check for `appTransactionID`
- Move `appTransactionID` inside iOS 18.4+ availability check in Swift code  
- Update TypeScript type to make `appTransactionID` optional for iOS versions below 18.4
The `appTransactionID` property was being accessed without version checking, which could cause crashes on iOS devices running versions below 18.4.
- Wrapped `appTransactionID` access in `if #available(iOS 18.4, *)` check
- Updated TypeScript interface to reflect that this property is optional
=> fix: add iOS 18.4+ availability check for appTransactionID

CONTRIBUTING.md, docs/CONVENTIONS.md, docs/docs/api/methods/core-methods.md, docs/docs/api/methods/listeners.md, docs/docs/api/use-iap.md, docs/docs/examples/complete-impl.md, docs/docs/examples/subscription-manager.md, docs/docs/getting-started/setup-android.md, docs/docs/getting-started/setup-ios.md, docs/docs/guides/faq.md, docs/docs/guides/getting-started.md, docs/docs/guides/ios-subscription-offers.md, docs/docs/guides/lifecycle.md, docs/docs/guides/migration.md, docs/docs/guides/purchases.md, docs/docs/guides/troubleshooting.md, docs/docs/intro.md, example/__tests__/core-functions.test.tsx, example/__tests__/purchase-flow.test.tsx, example/__tests__/subscription-flow.test.tsx, example/app/purchase-flow.tsx, example/app/subscription-flow.tsx, example/jest.setup.js, src/useIap.ts
- Replace all instances of `getProducts()` with `requestProducts({ skus, type: 'inapp' })`
- Replace all instances of `getSubscriptions()` with `requestProducts({ skus, type: 'subs' })`
- Update useIap hook to use requestProducts internally
- Keep deprecated methods for backward compatibility (will be removed in v3.0.0)
- Updated `useIap.ts` to use `requestProducts` internally while keeping deprecated methods
- Added deprecation warnings to the type definitions
- Updated `subscription-flow.tsx` to use the new API
- Updated test files to verify both new and deprecated APIs work
- Updated all documentation files to use `requestProducts`
- Added deprecation notices in API documentation
- Updated code examples throughout the docs
=> refactor: replace deprecated getProducts and getSubscriptions with requestProducts

CHANGELOG.md, docs/docs/api/methods/listeners.md, docs/docs/api/use-iap.md, docs/docs/guides/lifecycle.md, docs/versioned_docs/version-2.6/guides/lifecycle.md, ios/ExpoIapModule.swift, package.json, src/index.ts, src/modules/ios.ts, src/useIap.ts
- Fixed iOS build error where sendEvent was receiving incorrect argument type
- Changed from passing plain string to dictionary format with 'productId' key
1. Configure a promoted in-app purchase in App Store Connect
2. Install the app via TestFlight or development build
3. Access the app from App Store product page with promoted IAP
4. Verify the promoted product event is triggered with format: `{productId: 'com.example.product'}`
5. Check console logs or event listeners receive the correct data structure
closes #117 #118
=> fix: resolve iOS build error in promoted product event handler

.markdownlint.json, CHANGELOG.md, docs/docs/guides/ios-hot-reload-fix.md, ios/ExpoIapModule.swift, package.json, src/useIap.ts
This PR fixes race conditions on iOS when using concurrent StoreKit operations with `Promise.all` during hot reload.
During hot reload, concurrent IAP operations would fail:
```typescript
await Promise.all([
requestProducts({ skus: productIds }),
getAvailablePurchases()  // Returns empty or fails
]);
```
- Added proper state cleanup when `initConnection()` is called
- Implemented `ensureConnection()` pattern matching Android
- Fixed native module to handle hot reload state properly
- **iOS Native Module**: Added state management and cleanup logic
- **Documentation**: Added guide for iOS hot reload fix
- **Changelog**: Updated with version 2.7.6 and 2.7.7 changes
Tested on iOS device with hot reload enabled - concurrent operations now work correctly.
Resolve #130
=> fix: iOS hot reload issues with concurrent StoreKit operations
